name: Docker Image Test (Reusable Workflow)

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  check-and-build:
    uses: mac-lucky/actions-shared-workflows/.github/workflows/weekly-docker-builder-reusable.yml@master
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    with:
      app_name: caddy-cloudflare
      dockerhub_image: maclucky/caddy-cloudflare
      ghcr_image: ghcr.io/mac-lucky/caddy-cloudflare
      version_api_url: https://api.github.com/repos/caddyserver/caddy/releases/latest
      version_json_path: .tag_name
      version_prefix: v
      enable_schedule: true
      check_existing_image: true
      registry_to_check: dockerhub
